apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z9bw65h6c-java-quarkus
  janus-idp.io/tekton: z9bw65h6c-java-quarkus
  backstage.io/kubernetes-id: z9bw65h6c-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z9bw65h6c-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
